# main text of home
name: vvney
bio: A Girl who travels the world eating noodles

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: http://vveny.github.io
your url: http://vveny.github.io

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
github: https://github.com/vveny
email: viin99@naver.com

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
